# Generated by Django 4.0.4 on 2022-04-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book_review',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
