# Generated by Django 4.0.4 on 2022-04-30 19:49

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('reviews', '0002_review_book_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book_review',
            new_name='book_review_body_text',
        ),
        migrations.AddField(
            model_name='review',
            name='review_preview_text',
            field=models.CharField(default='', max_length=255, verbose_name='Post Preview Text'),
        ),
        migrations.AddField(
            model_name='review',
            name='topic_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Topic Tags'),
        ),
        migrations.DeleteModel(
            name='TopicTag',
        ),
    ]
