# Generated by Django 4.0.4 on 2022-04-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_review_preview_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_preview_text',
            field=models.TextField(default='', help_text='Max 255 characters', max_length=255, verbose_name='Post Preview Text'),
        ),
    ]
