# Generated by Django 4.0.4 on 2022-04-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_review_preview_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_date',
            new_name='post_date',
        ),
    ]
