# Generated by Django 4.0.4 on 2022-05-01 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_review_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 14, 20, 51, 234725), verbose_name='Date of Review'),
        ),
    ]
