# Generated by Django 4.0.4 on 2022-05-01 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_alter_review_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 14, 47, 34, 90853), verbose_name='Date of Review'),
        ),
    ]
