# Generated by Django 4.0.4 on 2022-05-01 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_alter_review_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 1, 15, 17, 45, 780726), verbose_name='Date of Review'),
        ),
    ]
