# Generated by Django 4.0.4 on 2022-04-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_book_review_review_book_review_body_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_preview_text',
            field=models.TextField(default='', max_length=255, verbose_name='Post Preview Text'),
        ),
    ]
