# Generated by Django 4.0.4 on 2022-05-01 18:16

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('reviews', '0007_review_book_cover_image_alter_review_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book_cover_image',
            field=models.ImageField(blank=True, default='', upload_to='images/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book_review_body_text',
            field=models.TextField(blank=True, verbose_name='Review Text'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='review',
            name='topic_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Topic Tags'),
        ),
    ]
