# Generated by Django 4.0.4 on 2022-05-01 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_review_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 14, 42, 36, 453357), verbose_name='Date of Review'),
        ),
    ]
