# Generated by Django 4.0.4 on 2022-05-12 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_alter_review_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 6, 56, 37, 662448), verbose_name='Date of Review'),
        ),
    ]
