# Generated by Django 4.0.4 on 2022-05-15 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_review_post_slug_alter_review_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_star_rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Star Rating'),
        ),
    ]
