# Generated by Django 4.0.4 on 2022-05-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_alter_review_book_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_cover_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name='Cover Image'),
        ),
    ]
