# Generated by Django 4.0.4 on 2022-05-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_alter_review_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book_review_body_text',
            field=models.TextField(blank=True, null=True, verbose_name='Review Text'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='review',
            name='post_slug',
            field=models.CharField(max_length=255, null=True, verbose_name='Slug'),
        ),
    ]
