# Generated by Django 4.0.4 on 2022-05-15 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_alter_review_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_star_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Star Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_preview_text',
            field=models.TextField(default='', help_text='Max 255 characters', max_length=255, null=True, verbose_name='Preview Text'),
        ),
    ]
